### ISSUE TITLE
Verify SQL created for complex id type is correct

### ISSUE THREAD

**Issue by gunnarmorling** [mincong-h/gsoc-hsearch#101]
enable output of generated SQL to verify whether/how it's working for complex id types

**Comment by mincong-h** [comment]
Seems to be OK.

```sql
Jul 12, 2016 9:01:00 PM org.hibernate.search.jsr352.internal.steps.lucene.ItemReader open
INFO: open reader for entityName=class org.hibernate.search.jsr352.entity.Company
Hibernate: 
    select
        this_.id as id1_0_0_,
        this_.name as name2_0_0_ 
    from
        Company this_ 
    where
        this_.id>? 
    order by
        this_.id asc limit ?
```

**Comment by gunnarmorling** [comment]
Hum, but how is that a complex id type if there only is a single "id"
column?

**Comment by mincong-h** [comment]
@gunnarmorling , if it is another primitive type like string, it works well. (I can't prove it right now, but the test example `Person.class` with id `String id` works with the above query). For more complex cases, like embeded id, I've no idea. So many I'll keep this issue opened until the problem is completely solved.

**Comment by mincong-h** [comment]
SQL syntax is OK for embedded composite PK (year, month, day), see [`MyDatePK.class`][1] :

```sql
12:47:21,786 INFO  [stdout] (Batch Thread - 9) Hibernate: 
12:47:21,786 INFO  [stdout] (Batch Thread - 9)     select
12:47:21,786 INFO  [stdout] (Batch Thread - 9)         this_.day as day1_2_0_,
12:47:21,786 INFO  [stdout] (Batch Thread - 9)         this_.month as month2_2_0_,
12:47:21,786 INFO  [stdout] (Batch Thread - 9)         this_.year as year3_2_0_,
12:47:21,786 INFO  [stdout] (Batch Thread - 9)         this_.weekday as weekday4_2_0_ 
12:47:21,786 INFO  [stdout] (Batch Thread - 9)     from
12:47:21,786 INFO  [stdout] (Batch Thread - 9)         MyDate this_ 
12:47:21,786 INFO  [stdout] (Batch Thread - 9)     where
12:47:21,786 INFO  [stdout] (Batch Thread - 9)         (
12:47:21,786 INFO  [stdout] (Batch Thread - 9)             this_.day>=? 
12:47:21,786 INFO  [stdout] (Batch Thread - 9)             and this_.month>=? 
12:47:21,786 INFO  [stdout] (Batch Thread - 9)             and this_.year>=?
12:47:21,786 INFO  [stdout] (Batch Thread - 9)         ) 
12:47:21,786 INFO  [stdout] (Batch Thread - 9)     order by
12:47:21,786 INFO  [stdout] (Batch Thread - 9)         this_.day asc,
12:47:21,786 INFO  [stdout] (Batch Thread - 9)         this_.month asc,
12:47:21,786 INFO  [stdout] (Batch Thread - 9)         this_.year asc limit ?
```

[1]: https://github.com/mincong-h/gsoc-hsearch/blob/340071866f73d93619c5314dddf23840ac6d1650/integrationtest/javaee-wildfly/src/test/java/org/hibernate/search/jsr352/test/entity/MyDatePK.java

**Comment by mincong-h** [comment]
## Example

There's a dataset `myDates` with the below dates. And the indexer does a checkpoint for every 3 items. 

year | month | day
--- | --- | ---
2015 | 07 | 10
2016 | 07 | 10
2016 | 07 | 12
2016 | 08 | 03
2016 | 08 | 04
2016 | 08 | 05

According to the above comment's `ORDER BY` syntax in HQL, the index order will be : 

year | month | day | checkpoint
--- | --- | --- | :---:
2016 | 08 | 03 | 
2016 | 08 | 04 | 
2016 | 08 | 05 | x
2015 | 07 | 10 | 
2016 | 07 | 10 | 
2016 | 07 | 12 | x

### ❌  ERROR
Imagine the job stop at the 3rd record and restart from the 4th, then it causes problem because the HQL statement for restart says : 

```sql
12:47:21,786 INFO  [stdout] (Batch Thread - 9)     where
12:47:21,786 INFO  [stdout] (Batch Thread - 9)         (
12:47:21,786 INFO  [stdout] (Batch Thread - 9)             this_.day>=? 
12:47:21,786 INFO  [stdout] (Batch Thread - 9)             and this_.month>=? 
12:47:21,786 INFO  [stdout] (Batch Thread - 9)             and this_.year>=?
12:47:21,786 INFO  [stdout] (Batch Thread - 9)         ) 
```

Which means that the restart point will take care none the rest, since July (07) is smaller than August (08). So the query is wrong. I need to redesign the HQL / Criteria.

**Comment by mincong-h** [comment]
Single PKs are OK (String, int, double ...). See issue #145 for composite PK.
