### ISSUE TITLE
Investigate partitioning within one entity types

### ISSUE THREAD

**Issue by gunnarmorling** [mincong-h/gsoc-hsearch#104]
* Have a parameter for the number of partitions
* Focus on numeric ids for now
* Add `WHERE mod(id) = n` to the select query of the producers, so each partition only works on one remainder of the id mod
* Investigate hash-based approach for other id types

**Comment by mincong-h** [comment]
I tried to implement this parallel processing this afternoon, but with a more generic approach. I'll explain the mechanism in the second paragraph, but let me explain first why I didn't use the modulo approach ?

## Initial propose

The first point is I don't know how to translate `WHERE mod(id) = n` into Hibernate criteria. The current implementation uses the `ScrollableResults`, obtained from Hibernate criteria. I didn't figure out how to embed the where condition with `MOD( ... )` expression and the identifier name is dynamic. Maybe something like this ?

```java
String sql = String.format( "WHERE MOD(%s) > %d", idName, checkpointId );
scroll = ss.createCriteria( entityClazz )
        .add( Restrictions.sqlRestriction( sql ) )
        .addOrder( Order.asc( idName ) )
        .setReadOnly( true )
        .setCacheable( true )
        .setFetchSize( 1000 )
        .setMaxResults( maxResults )
        .scroll( ScrollMode.FORWARD_ONLY );
```

Then the second point is how to deal with other type. And I don't know how to do the hash-based approach.

The 3rd point is the customized case. If the ids are not evenly distributed (e.g. more `mod(id) = 2` than `mod(id) = 1`), then the computing resources are not balanced. Partition 2 might takes much longer then partition 3.

So based on the above reasons, I had been thinking about it for more than 2 hours without any idea.

## New propose

But then, I went to sleep and found a new approach in my dream ! 😪 😎  That's to scroll the obtained entities using `ScrollableResults#scroll( int )` for all the partitions within the same entity type. The scroll uses the principal of division-remainder too. At the first read, it scrolls to an offset position, which is similar to the remainder `mod(id) + 1`. Then, starting from the second read, it scrolls a fix interval, which equals to the number of partition `n`.

### Example

Now, let's see an example about how it works. Assume that we've 10 companies to index and we need 2 partitions. Then we have : 

* partition-0
  * `offset` = partition-id = 0
  * `interval` = number of partiton = 2
* partition-1
  * `offset` = partition-id = 1
  * `interval` = number of partiton = 2

Then the workflow will be : 

```
  companies:  [ 1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 , 10 ]
partition-0:    x       x       x       x       x

  companies:  [ 1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 , 10 ]
partition-1:        x       x       x       x       x
```

Each partition starts from position `position = 1 + offset`, then each time it scrolls to next interval `position += interval` and it works until the last items found. This approach should works with non-numeric id type too. And there won't be even distribution problem, because it is based on the scrollable results.

The only problem is that we are using the same scrollable results for all partitions within this entity type, it fetches more rows than needed.

**Comment by mincong-h** [comment]
The discussion has been moved to #108.
