### ISSUE TITLE
Use remainder approach as discussed, not current offset scheme

### ISSUE THREAD

**Issue by gunnarmorling** [mincong-h/gsoc-hsearch#107]

**Comment by mincong-h** [comment]
I'm currently blocked in this approach. On one side, for PK in non-numeric type, a hash function is required for obtaining the scrollable result. And on the other side, the scrollable result interacts directly with the database via JDBC, so the hash function should be an ANSI build-in function of  the database. I don't find such function so far.

## Why not do the hash code in Java ?

I can implement a `hashCode()` function in Java and handle the comparison. But that is not even a solution because it requires a full-loading of all the target entities in memory for hash comparison. Which is exactly the anti-pattern of a batch processing.

I suggest to suspende this approach and keep working on other fields. The related code can still be found in branch _issue-107_.
