### ISSUE TITLE
Address TODO in ProgressAggregator#analyzeCollectorData()

### ISSUE THREAD

**Issue by gunnarmorling** [mincong-h/gsoc-hsearch#134]
> TODO Currently, percentage is not supported for the restarted job
> // instance, because collected data is lost after the job stop.

There is `setPersistentData()` which may help with that.

**Comment by mincong-h** [comment]
This issue has been fixed using `setPersistentUserData(Serializable)`. The idea is to use different persistent data for main thread and partition threads:

* For main thread, the persistent data is `StepProgress`.
* For partition threads, the persistent data is `StepContextData` <sup>[1]</sup>

However, it's not that simple: in order to use and update the `StepProgress` at the end of each chunk, we need a transient data instead of persistent. So, there's a transformation between transient and persistent data, written in `StepProgressSetupListener`. The new relation of all the components can be seen through the Job XML:

```xml
...
<step id="produceLuceneDoc" next="afterChunk">
  <!-- New -->
  <listeners>
    <listener ref="stepProgressSetupListener">
      <properties>
        <property name="isJavaSE" value="#{jobParameters['isJavaSE']}" />
      </properties>
    </listener>
  </listeners>
  <chunk checkpoint-policy="custom">...</chunk>
  <partition>...</partition>
</step>
...
```

<sup>[1]</sup> It will be renamed to `PartitionContextData` later.
