### ISSUE TITLE
Use more specific class names

### ISSUE THREAD

**Issue by gunnarmorling** [mincong-h/gsoc-hsearch#135]
Rather than `ItemProcessor` e.g. `LuceneDocumentCreationProcessor`.

**Comment by mincong-h** [comment]
What about : 

* `ItemReader` -> `EntityExtractor`
* `ItemProcessor` -> `LuceneWorkProducer`
* `ItemWriter` -> `LuceneWorkExecutor`

**Comment by gunnarmorling** [comment]
I'd like if the names gave an indication of what they are:
EntityExtractionReader, LuceneDocumentProducingProcessor,
IndexUpdating(Item)Writer.

But I'll leave it to your judgement :)

**Comment by mincong-h** [comment]
Hi @gunnarmorling, based on your feedback, I think the below names are not bad : 

*  `EntityReader`
*  `LuceneDocProducer`
*  `LuceneDocWriter`

I agree with you that the most important consideration in naming is that : the name fully and accurately describe the role of the class. That's why I think we should keep the words `reader` & `writer`. As for `processor`, I think it would be duplicate with producer, may be not a good idea to keep it. No matter how the names of these classes will be, the full job description is available at `META-INF/mass-index.xml`. So it shouldn't be too hard for developers to find their roles : 

```xml
<step id="produceLuceneDoc" next="afterChunk">
    <chunk checkpoint-policy="custom">
        <reader ref="entityReader">
            ...
        </reader>
        <processor ref="luceneDocProducer">
            ...
        </processor>
        <writer ref="luceneDocWriter">
            ...
        </writer>
        ...
    </chunk>
</step>
```

However, your opinion might be better. Can you give me final names for these classes ? I'll rename them. And then, let's refactor them when the project is integrated into the Hibernate Search.

**Comment by gunnarmorling** [comment]
Your names seem good, go for them :)

**Comment by mincong-h** [comment]
Thanks @gunnarmorling. Done now. :)
