### ISSUE TITLE
Integration with FTS and FTEM

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#147]
The existing mass indexer is integrated with full-text session (FTS) and full-text entity manager (FTEM). The new one should be available to do the same thing : 

``` java
fullTextSession.createIndexer().startAndWait();
fullTextEntityManager.createIndexer().startAndWait();
```

**Comment by mincong-h** [comment]
Batch indexing job does not use the same session as the provided FTS or FTEM. So it doesn't make sense to integrate this job into the full-text session. The separation of batch indexing / full-text session also allows users to understand the difference between these two components. Therefore, this issue should be marked as `wontfix`. Am I right, @yrodiere ?

**Comment by yrodiere** [comment]
@mincong-h You're right, though following this reasoning we should also remove the `createIndexer` method for the older mass indexer (since it also doesn't use the session we create it from).
Anyway, there is another reason for not wanting to add a method for our JSR-352 mass indexer: the JSR-352 module is and will stay an optional one, while `FullTextSession` is located in the core 'hibernate-search-orm' module. Thus we can't expose APIs related to the JSR-352 module in `FullTextSession`.
Closing.
