### ISSUE TITLE
Avoid SNAPSHOT versions among the dependencies

### ISSUE THREAD

**Issue by Sanne** [mincong-h/gsoc-hsearch#153]
I noticed the current build is requiring WildFly version `11.0.0.Alpha1-SNAPSHOT`. This should be avoided.
To resolve this we probably need to wait for the first Alpha release of WildFly 11 ?

**Comment by mincong-h** [comment]
I switched the WF dependency to `11.0.0.Alpha1-SNAPSHOT` because of issue [WFLY-7000][1], which is fixed only in that version. But you're right @Sanne, I should revert to 10.0.0.Final before the release of WF11.

Actually, I've a work-around solution for that issue, so WF10 is OK.

[1]: https://issues.jboss.org/browse/WFLY-7000

**Comment by mincong-h** [comment]
Dummy job xml files have been added to integration modules so that WF can enable the job resolution for both users's deployment and WF modules.

FYI, these dummy xml files are a work-around solution for WF10. They won't be needed after the resolution of WFLY-7000 in 11.0.0.Alpha1.
