### ISSUE TITLE
Sorting order of the parallel partitions might need to include multiple fields

### ISSUE THREAD

**Issue by Sanne** [mincong-h/gsoc-hsearch#155]
```
String fieldID = MassIndexerUtil.getIdName( clazz, session );
scroll = ss.createCriteria( clazz )
   .addOrder( Order.asc( fieldID ) )
       .setProjection( Projections.id() )
```

The projection is on the `Projections.id()`, which is correct but one has to consider that this might be a composite object made of multiple attributes. The `Order` clause should target the same, as we might have the id defined on multiple Id fields.

The parallel loaders should then also be adjusted to load elements in the same consistent order.

**Comment by mincong-h** [comment]
I mentioned this in issue #145 Cover the composite PK in EntityReader. However, I've no idea how to include multiple fields. Let's discuss during the meeting.

**Comment by yrodiere** [comment]
I think this is already solved, because the orders by the embeded id property and the name of this property is properly retrieved (see #167). From what I can see in the code, `Order.asc` handles composite properties just fine (with some quirks, as mentioned in #145, but I'd argue that's more an Hibernate ORM issue than a Hibernate Search one).

@mincong-h Maybe we could just add a test for mass indexing an entity with an `@EmbeddedId`? And then mark this issue as solved?

**Comment by Sanne** [comment]
+1 to add a test to cover such special cases, would make it far easier to then asses how far this is a problem.

Yet even if we classify this as an "Hibernate ORM issue", we'd need to either fix ORM or find an alternative solution, or we can't use an approach which doesn't work ;-)
I'd be fine to use it if we can detect the dangerous situation and abort, at least people will have options.

**Comment by yrodiere** [comment]
> Yet even if we classify this as an "Hibernate ORM issue", we'd need to either fix ORM or find an alternative solution, or we can't use an approach which doesn't work ;-)

If it doesn't work, sure. I meant that the actual order may be a bit surprising because of a Hibernate ORM issue (see #145), but the partitioning might actually work fine. In this case, we can live with the ORM issue.

**Comment by mincong-h** [comment]
> Maybe we could just add a test for mass indexing an entity with an `@EmbeddedId`?

Test added but it should fail.

**Comment by yrodiere** [comment]
@mincong-h Could you please show me where this failing test is? I couldn't find any ignored tests on master, so I guess it's located in another branch?

**Comment by mincong-h** [comment]
Sorry for this inconvenience, I didn't precise the test location. This is test is located in branch `issue-155`, written in commit 8f45989. or you can check [here][1] directly. I didn't split the test with the existing one. If I had done this, this would be much clearer for you. Will do the next time.

Basacially, I added an entity type `MyDate` of which the id is embedded `MyDateId`. The test job is:
1. started for the first time, some of the dates of type `MyDate` are indexed, but not all of them
2. interrupted by byteman
3. restarted again. After the restart, indexing continue. However, the number of Sundays in 2017 indexed is different from the expected results, as we can found in [this build in Travis CI][2]. This is because [`MyDate` is not fully indexed.][3]

[1]: https://github.com/mincong-h/gsoc-hsearch/blob/8f45989be2fc912e6423d7757e4f05d88911928a/core/src/test/java/org/hibernate/search/jsr352/RestartChunkIT.java#L120-L160
[2]: https://travis-ci.org/mincong-h/gsoc-hsearch/builds/192140872#L780-L785
[3]: https://travis-ci.org/mincong-h/gsoc-hsearch/builds/192140872#L764

**Comment by yrodiere** [comment]
@mincong-h Thank you. So, indeed the test fails, but indexing `MyDate` also fails in a simpler context without byteman rules.
The reason is, the way Hibernate ORM translates ordering isn't adequate at all, regardless of the order of columns. I should have seen it earlier, but... I guess I didn't pay enough attention.

For instance, in your test, there are two partitions: (-infinity,2017-09-21) and [2017-09-21,+infinity).
This is results in the following two conditions:

 * Partition 1: `WHERE day<21 and month<9 and year<2017`
 * Partition 2: `WHERE day>=21 and month>=9 and year>=2017`

But... What of 2017-10-01? It matches neither condition.

The proper conditions would have been:

 * Partition 1:
   ```
   WHERE year<2017
     OR (year=2017 AND month<9)
     OR (year=2017 AND month=9 AND day<21)
   ```
 * Partition 2:
   ```
   WHERE year>2017
     OR (year=2017 AND month>9)
     OR (year=2017 AND month=9 AND day>=21)
   ```

Which admittedly is a lot to ask from Hibernate ORM.

I think we should implement this behavior ourselves:

 1. From the metadata, we should detect cases where the id property is composite
 2. Whenever this happens, we should retrieve the list of the sub-properties from the metadata (`sessionFactory.getMetamodel().entity( entityClass ).getIdClassAttributes()`)
 3. In the partition mapper, when retrieving the IDs, we should explicitly project and order on those sub-properties, and set the partition bounds with the result (which will be an `Object[]`, presumably)
 4. In the EntityReader, we should build the query for each partition in the same way as the example above.

**Comment by yrodiere** [comment]
Closing, moved to JIRA: https://hibernate.atlassian.net/browse/HSEARCH-2615
