### ISSUE TITLE
Avoid a static reference to the EMF in JobSEEnvironment

### ISSUE THREAD

**Issue by Sanne** [mincong-h/gsoc-hsearch#156]
Even in JavaSE it is possible, and quite common, to have multiple different persistent units.

So we need to avoid using a static reference to "the" EMF as this is ambiguous.

**Comment by mincong-h** [comment]
@Sanne, could you give me some hint about the modification: how can I achieve this requirement?

**Comment by yrodiere** [comment]
I hope you'll forgive me, but I'm going to state the obvious in order to check I understand the issue correctly. Please tell me if I got something wrong.

### The issue

The issue here is about having, in a job, an element of context that is not serializable.

The `JobContext` class only allows to store strings (as required by the spec) or simple serializable types (in the JBeret implementation) using `jobContext.getProperties()`. The reason is probably that the job context must be serialized in database in order to allow restarting of a failed job.

What we have on our hands here is a much more complex object that cannot be serialized, and that is provided as part of the job's parameters (see `org.hibernate.search.jsr352.BatchIndexingJob.Builder.underJavaSE(EntityManagerFactory, JobOperator)`: the `EntityManagerFactory`.

CDI allows that object to be injected automatically (when using Java EE for instance), but when CDI is not available (for instance when using plain Java SE), we have to find another solution.

### The obvious solution that won't work

A trivial solution would have been to create a new factory for each chunk. It probably hasn't been implemented this way because the performance cost would be huge, and because having multiple `EntityManagerFactory` for the same persistent unit probably isn't a good idea.

### The current solution

The current solution uses a static, global variable to store the `EntityManagerFactory`, and it cannot stay that way because this prevents two instances of the job to be launched simultaneously on the same JVM (for instance for different applications).

### The requirements for the ideal solution

Ideally, the solution should:

 * use a single `EntityManagerFactory` accross a given job
 * allow different jobs to use different factories

**Comment by Sanne** [comment]
> because having multiple EntityManagerFactory for the same persistent unit probably isn't a good idea.

Right. For example, the Lucene IndexWriter would need to be shared, or a second instance would be locked out as the index is locked when an IndexWriter opens it. At the very least we would need to shut down the IndexManagers on the main application, which is not desirable.

**Comment by mincong-h** [comment]
### The issue

> The issue here is about having, in a job, an element of context that is not serializable.

Yes.

> The `JobContext` class only allows to store strings (as required by the spec) or simple serializable types (in the JBeret implementation) using `jobContext.getProperties()`. The reason is probably that the job context must be serialized in database in order to allow restarting of a failed job.

Yes. I think there're several reasons for only allowing strings storage:

- Ability for restarting a batch of which the status is _STOPPED_ or _FAILED_. (§10.8 Restart Processing, spec page 89)
- Starting a batch job from CLI, where job parameters are given as string arguments. Here're 2 examples from [JBoss WildFly][wildfly-shell] and [IBM WAS Liberty][ibm-shell].
- Scheduling support to allow batch jobs running at night or any off peak hours. In JBeret, we've [jberet-schedule][jberet-schedule]. But scheduling is not included in the spec.

> What we have on our hands here is a much more complex object that cannot be serialized, and that is provided as part of the job's parameters (see `org.hibernate.search.jsr352.BatchIndexingJob.Builder.underJavaSE(EntityManagerFactory, JobOperator)`: the `EntityManagerFactory`.

> CDI allows that object to be injected automatically (when using Java EE for instance), but when CDI is not available (for instance when using plain Java SE), we have to find another solution.

Yes. I'm surprised how well you understand the situation! But yes!! :smile: :100:

### The obvious solution that won't work

> A trivial solution would have been to create a new factory for each chunk. It probably hasn't been implemented this way because the performance cost would be huge, and because having multiple `EntityManagerFactory` for the same persistent unit probably isn't a good idea.

Yes.

### The current solution

> The current solution uses a static, global variable to store the `EntityManagerFactory`, and it cannot stay that way because this prevents two instances of the job to be launched simultaneously on the same JVM (for instance for different applications).

Thanks for your explanation. I didn't aware of it.

Let's me describe why I used the current solution: As I don't know much about _static_ in Java, what I did is to use a singleton design-pattern copied from Stack Overflow (it's ashamed but well...). And I actually [asked feedback on Stack Overflow][so-39770987], but have no response. You can copy the above explanation to answer me there, easy 25 points to earn! :sunglasses:

### The requirements for the ideal solution

> Ideally, the solution should:
>
> * use a single `EntityManagerFactory` accross a given job
> * allow different jobs to use different factories

Yes. I agree with you. Additionally, the ideal solution should work under both Java SE and Java EE, so avoid CDI.

[wildfly-shell]: https://docs.jboss.org/author/display/WFLY10/Batch+(JSR-352)+Subsystem+Configuration?_sscc=t
[ibm-shell]: https://github.com/WASdev/sample.batch.bonuspayout/blob/35febaeb4c8c853fc3b77f1d71914d7e29288995/batch-bonuspayout-application/src/test/java/com/ibm/websphere/samples/batch/test/BonusPayoutIT.java#L114-L117
[jberet-schedule]: https://github.com/jberet/jsr352/tree/master/jberet-schedule
[so-39770987]: https://stackoverflow.com/questions/39770987/did-i-avoid-a-static-reference-to-the-emf

**Comment by Sanne** [comment]
I agree about avoiding the need for CDI if that's possible, as the less dependencies we have it's better. But keep in mind that CDI works fine in JavaSE.

**Comment by yrodiere** [comment]
@Sanne Yes, CDI can work in a JavaSE environment, but still it would be a shame if Spring users, for instance, were forced to use a CDI implementations besides Spring DI... And in order to stop using hardcoded PU names (#163), we'll probably have to use CDI-specific (JSR-299) interfaces that are not implemented by Spring DI or Guice for instance.

Anyway, I had a look at the spec, and I don't think there is a generic, clean way to pass non-serializable parameters to a job. You can use injection, but even then there's no generic way to retrieve the `EntityManagerFactory` dynamically (i.e. with a parameterized unit name): in CDI you must inject a `javax.enterprise.Instance`, which is CDI-specific, in Spring you'd inject an `ApplicationContext` or `BeanFactory`, and so on.

One solution, though, would be to maintain a `ConcurrentMap` (unit name => `EntityManagerFactory`) instead of a singleton `EntityManagerFactory` in `JobSEEnvironment`. Either we'd ask users to populate this map themselves, or (maybe better?) we could hook into Hibernate ORM with a `org.hibernate.integrator.spi.Integrator` that could maintain this map itself.
That last part seems a bit too easy, though... Maybe this solution will be too fragile?

I'll try to submit a PR implementing this solution in the next few days.
@Sanne, do you think the solution is technically sound? Especially the part about adding an `Integrator` to build a map of all `EntityManagerFactory`s (or `SessionFactory`s actually)...
@mincong-h , do you see any problem with the solution?

**Comment by mincong-h** [comment]
I'd like to ensure I understand your solution before going deeper discussion in the code:

1. Your solution is located in branch `yrodiere/i156`
2. It maintains a distinction between JavaSE and JavaEE before the job start.
  a. If user is under JavaSE, then `EntityManagerFactory` and `isJavaSE` are required.
  b. Else, we use a hardcoded EMF `h2` through `@PersistenceUnit`
3. After the job started, `org.hibernate.search.jsr352.internal.JobContextSetupListener.java` is called to setup the EMF as part of the `JobContextData`. The setup is different between JavaSE and JavaEE.
4. In the rest of the job, we call EMF through `JobContextData` directly.

---

If everything is OK, then I continue... I'm a little bit worried about the serialization of `EntityManagerFactory` in case of job restart.

- If only the name of `PersistenceUnit` were stored as String in the job properties, it might cause problems to look up the `EntityManagerFactory`, but it would never cause problem in serialization.
- If an instance of `EntityManagerFactory` were stored, I don't know how EMF would be stored. What information is serialized and will it have impact on performance?

Then I think the step _2.b_ won't work, because if CDI is disabled, then `@PersistenceUnit` will fail or NullPointerException, won't it? But if this is a temporary solution, that's OK, we should discuss it in #86 .

And the most important one: the lifecycle and scope of JobContext.

In Chapter 9.4.1.1 Batch Context Lifecycle and Scope, page 76-77:

> JobContext
> There is one JobContext per job execution. It exists for the life of a job. **There is a distinct JobContext for each sub-thread of a parallel execution (e.g. partitioned step).** // ⚠️ I don't know this will cause problem to EMF. Will all the job context reference the same EMF? Problem with thread-dafe? Will batch runtime try to clone the EMF while creating distinct job context instances for each sub-thread?

**Comment by yrodiere** [comment]
> Then I think the step 2.b won't work, because if CDI is disabled, then @PersistenceUnit will fail or NullPointerException, won't it? But if this is a temporary solution, that's OK, we should discuss it in #86 .

Well, the tests pass: https://travis-ci.org/yrodiere/gsoc-hsearch
Anyway, yes, it's temporary.

> I'd like to ensure I understand your solution before going deeper discussion in the code:

Well, it's not quite that:

 * Only *part* of the solution is in `yrodiere/i156`: I haven't worked on the concurrent map thing yet.
 * I intend to change the way the entity manager factory is retrieved from the job, and the solution may only require that we provide the persistence unit's *name* before the job starts. Which would make the parameters building quite simpler. See the third paragraph in my previous post for more details.

> I'm a little bit worried about the serialization of EntityManagerFactory in case of job restart.
> 1. If only the name of PersistenceUnit were stored as String in the job properties, it might cause problems to look up the EntityManagerFactory, but it would never cause problem in serialization.
> 2. If an instance of EntityManagerFactory were stored, I don't know how EMF would be stored. What information is serialized and will it have impact on performance?

I intend to store the EntityManagerFactory in the *transient* job context data, so it'll be the first option. I expect the `JobContextSetupListener` to be executed upon restart, so there shouldn't be any problem with the EMF not being available in the job context. If it's not executed upon restart, we'll have to find a workaround indeed. But if it's the case, we already have problems with the current implementation, because we already store data in the job context transient data.

> There is a distinct JobContext for each sub-thread of a parallel execution (e.g. partitioned step). // :warning: I don't know this will cause problem to EMF. Will all the job context reference the same EMF? Problem with thread-dafe? Will batch runtime try to clone the EMF while creating distinct job context instances for each sub-thread?

I think the job context data is *copied* to each sub-thread, otherwise we would already have issues (we already store stuff in the job context transient data). In the solution I proposed, yes, every job context in every thread will reference the same EMF.

About thread safety... from what I can see, `SessionFactoryImpl` (the class doing all the work for Hibernate ORM's implementation of `EntityManagerFactory`) is thread-safe. From the javadoc of `org.hibernate.internal.SessionFactoryImpl`:

```
 * This class must appear immutable to clients, even if it does all kinds of caching
 * and pooling under the covers. It is crucial that the class is not only thread
 * safe, but also highly concurrent. Synchronization must be used extremely sparingly.
```

The actual implementation of `EntityManagerFactory` doesn't seem totally thread safe, but as long as we only use `SessionFactory` I think we should be fine.

Anyway, it will probably be simpler if I just go on, implement the thing, and submit a PR. Then we'll be able to discuss the actual piece of code.

**Comment by yrodiere** [comment]
For your information, I'm still working on this (though not full-time). A clean and easy solution seems less and less likely.
The next thing I'll try will be to make it mandatory for users to provide a component that will be used in the job to retrieve the entity manager. We may provide an implementation for CDI, and we'll probably leave it to someone else to code one for Spring, Guice, etc. I'll let you know once I know more about what's actually possible (hint: not much :p).

**Comment by mincong-h** [comment]
> I intend to change the way the entity manager factory is retrieved from the job, and the solution may only require that we provide the persistence unit's name before the job starts. Which would make the parameters building quite simpler. See the third paragraph in my previous post for more details.

Ah, I understand your concurrent map now. Key = PU name, value = EMF. Great idea! 👍 

> I expect the `JobContextSetupListener` to be executed upon restart, so there shouldn't be any problem with the EMF not being available in the job context.

According to the spec's chapter _11 Job Runtime Lifecyle_ > _11.3 Job Processsing_ (page 106):

```
1. <Create JobContext>
2. <Store job level properties in JobContext>
3. <->[JobListener.beforeJob...] // thread A
4. <processs execution elements>
5. <->[JobListener.afterJob...] // thread A
6. <Destroy JobContext>
```

Job listeners should always be executed before processing execution elements, as described at step 3. No matter the job execution is a first start or a restart, the same processing rules should be applied. However, this is just my personal understanding. We should find more explicit description / test it via other implementation(s).

> For your information, I'm still working on this (though not full-time). A clean and easy solution seems less and less likely...

Thanks for your help, @yrodiere. I'm very glad that you're interested in this project and providing so many supports. I'm looking forward to see your progress :smiley:
