### ISSUE TITLE
Investigate on how multithreading can be tuned within a job

### ISSUE THREAD

**Issue by yrodiere** [mincong-h/gsoc-hsearch#169]
In particular, the readers and processors should use much more threads than the writer.
We should see how JBeret and other impls handle threads:

 * Is it fully static? For instance one third for reading, one third for processing, and one third for writing?
 * Is it dynamic? For instance we have the static configuration initially, and if the processors threads start to block because they don't have enough input, some processor threads are turned into reader threads instead?
 * Can it be tuned?

In the case of Hibernate Search mass indexer, we should have much more threads attributed to reading and processing than to writing, because writing to the Lucene indexes is surprisingly CPU intensive. It's Sanne that says that, not me, so you can trust it ;)

**Comment by Sanne** [comment]
good summary, thanks.

About "dynamic":
I don't expect threads to "move" between task types as that would be unnecessary, in terms of efficiency it's totally fine to park threads which have nothing to do, while moving resources could be dangerous, like introducing deadlocks.
But it would be useful to have management operations which could allow an external agent to reduce / increase the amount of threads dedicated to a certain task.

**Comment by mincong-h** [comment]
> In particular, the readers and processors should use much more threads than the writer.

We can't. In partitioned chunk processing, a partition is always composed by 1 reader + 1 processor + 1 writer, **these 3 objects work in the same thread.** Therefore, we CANNOT have more threads for readers / processors and less threads for writer. I'll try to explain why through my understanding and the spec.

## Partitioning mechanism in JSR 352

First, let's give threads some names:

- _Thread Px_: a partitioned chunk thread
- _Thread A_: the main thread

**Thread Px** is responsible for the chunk processing: one item is read by an `ItemReader`, processed by by an `ItemProcessor` and aggregated; then another item is read by an `ItemReader`, processed by by an `ItemProcessor` and aggregated; ... until the checkpoint of N aggregated items is reached. Now, the `ItemWriter` in _Thread Px_ is called to write the list of N items. These N items processed between checkpoints are referred to as a _"chunk"_. During a chunk in _Thread Px_:

- `ItemReader` has been called N times
- `ItemProcessor` has been called N times
- `ItemWriter` has been called 1 time

**Thread A**, the main thread, it controls the partitioning: partition mapping, collection, analysis, reduction through `PartitionMapper`, `PartitionCollector`, `PartitionAnalyser`, `PartitionReducer`. Everything is on the main thread, the "controller" thread.

## ETL always in the same thread

Now, let's see the workflow of _Partitioned Chunk Processing_ (§11.7, Spec page 109-110):

    1. <Create StepContext>
    2. <Store step level properties in StepContext>
    3. <->[StepListener.beforeStep...] // thread A
    4. <->[PartitionReducer.beginPartitionedStep] // thread A
    5. <->[PartitionMapper.mapPartitions] // thread A
        // per partition - on thread Px:
        a. [<begin transaction> ]
        b. <->ItemReader.open // thread Px
        c. <->ItemWriter.open // thread Px
        d. [<commit transaction> ]
        a. <repeat until no more items> {
            i. <begin checkpoint [<begin transaction> ]>
            ii. <repeat until commit criteria reached> {
                1. <->ItemReader.readItem // thread Px
                2. <->ItemProcessor.processItem // thread Px
                3. <add item to buffer>
            iii. }
            iv. <->ItemWriter.writeItems // thread Px
            v. <->[ItemReader.checkpointInfo] // thread Px
            vi. <->[ItemWriter.checkpointInfo] // thread Px
            vii. <Store (partition-local) StepContext persistent area>
            viii. <commit checkpoint (commit transaction)>
            ix. <->[PartitionCollector.collectPartitionData] // thread Px
        e. }
        f. [<begin transaction> ]
        g. <->ItemWriter.close // thread Px
        h. <->ItemReader.close // thread Px
        i. [<commit transaction> ]
        j. <->[PartitionCollector.collectPartitionData] // thread Px transaction> ] // thread A
    6. [<begin
    7. // Actions 9-12 run continuously until all partitions end.
    8. // when collector payload arrives:
    9.        <->[PartitionAnalyzer.analyzeCollectorData] // thread A
    10. // when partition ends:
    11.       <->[PartitionAnalyzer.analyzeStatus] // thread A
    12. // Remaining actions run after all partitions end:
    13. // if rollback condition occurs:
    14.       <->[PartitionReducer.rollbackPartitionedStep] // thread A
    15.       [<rollback transaction >]
    16. // else not rollback
    17. <->[PartitionReducer.beforePartitionedStepCompletion] // thread A
    18. [<commit transaction> ] // thread A
    19. <->[PartitionReducer.afterPartitionedStepCompletion] // thread A
    20. <->[StepListener.afterStep...] // thread A
    21. <Store StepContext persistent area>
    22. <Destroy StepContext>

As you can see, we CANNOT freely control the number of threads `x`. Item reader, processor and writer work in the same thread _thread Px_.

**Comment by mincong-h** [comment]
> Is it fully static? For instance one third for reading, one third for processing, and one third for writing?

The configuration is static, the number of threads `maxThreads` is given as a job parameter before the start of the job. User can ask for as many threads as they want, but _the batch runtime cannot guarantee the requested number of threads are available; it will use as many as it can up to the requested maximum (Spec, page 34)_. According to [this answer on Stack Overflow][so]: At Wildfly, it has a default thread pool setting of max 10 threads. This pool is not only shared between partitioned steps, it is also shared between batch jobs.

[so]: https://stackoverflow.com/questions/38675757/how-to-define-a-good-partition-plan-to-ensure-cpu-balance-in-jsr-352

**Comment by mincong-h** [comment]
> Is it dynamic? For instance we have the static configuration initially, and if the processors threads start to block because they don't have enough input, some processor threads are turned into reader threads instead?

Input of a thread _Thread Px_ is given as a partition, through the `PartitionMapper` (see above workflow, step 5). If _Thread Px_ don't have input, it should be released and returned to the batch runtime.

> ... some processor threads are turned into reader threads instead?

Each partition thread has a Reader, Processor, Writer instance. As described in the above workflow at steps `5.a.ii.1` and `5.a.ii.2`, if one processor finishes processing an item, the thread will be used for reading the next item.

**Comment by mincong-h** [comment]
> Can it be tuned?

In my opinion, the threads cannot be tuned. But the number of partitions can. Before going into detail, let me explain the difference between threads, partition, chunk in JSR 352.

- Partition is a unit of works to do. It's a product, produced by the `PartitionMapper`. A partition has at least one chunk.
- Chunk is a group of items inside a partition. Checkpoint is reached when a chunk is finished.
- Thread is used to run partitions. It's a consumer, it consumes partitions, one per time. Thread can consume 0 to N partitions depending on batch runtime. If a thread is available and there're remain partitions to do, batch runtime will assign one partition to this thread. If a thread is consuming a partition, it won't consume another partition until the current one is finished.

So can it be tuned? 🤔

**For thread**, the configuration is static. There're not much we can do. We can only request the maximum number of threads to batch runtime. It will use as many as it can up to the requested maximum.

**For partitions**, the configuration is dynamic. The partition plan is done through `PartitionMapper`, which is a runtime calculation and completely dynamic at each new start of the job (not restart). **So, the essential point is ensure that all the threads are occupied, so that the batch job can be finished ASAP.**

> How this is done in the current code?

The current code makes the partition size very small. So, one thread can handle a partition quickly and be assigned to handle another partition. User can setup the property `rowsPerPartition`, and based on this property, partition mapper give a number of partitions. The value `rowsPerPartition` is unique for all the entity type. In order to be performant, the value shouldn't be too big.

    partitions = Sum ( Rows of Entity clz / Row Per Partitions )

Let's take an example. We've 2 entity types: `Employee` and `Payroll`.

Case | Entity Type | Rows In Database | Rows Per Partitions | Partitions
---- | ---- | ----: | ----: | ----:
Good | Employee | 1,000 | 1,000 | 1
Good | Payroll | 239,000 | 1,000 | 239
Total | - | - | - | 240
Bad | Employee | 1,000 | 500,000 | 1
Bad | Payroll | 239,000 | 500,000 | 1
Total | - | - | - | 2

So if we have 9 threads for this example, one thread will be the main thread A, and 8 thread of partitions.

- In the good configuration, on average, each _Thread Px_ handles 240 / 8 = 30 partitions.
- In the bad configuration, 2 _Thread Px_ handles each 1 partitions, 6 partitions are never used. The thread which handles the `Payroll` will finish much later than the other thread.

**Comment by mincong-h** [comment]
I previously asked a question on Stack overflow about [How to define a good partition plan to ensure CPU balance in JSR 352?][1]. And I got a very detailed answer from Carlitos Way. Maybe you can take a look on it.

[1]: https://stackoverflow.com/questions/38675757/how-to-define-a-good-partition-plan-to-ensure-cpu-balance-in-jsr-352

**Comment by yrodiere** [comment]
@mincong-h Thanks for the detailed explanation.

If I understood correctly, we can't assign much more threads to reading/processing than to writing, but we actually shouldn't care. The fact that each partition (reading, processing *and* writing) is handled in a single threads means that we won't have "writing threads" waiting for reading/processing threads to be done with their job. Which, ultimately, is all that matters.

So I guess we can close this: you proved there's nothing to do. @Sanne, I'll let you reopen if you disagree?

I opened another ticket on a related subject, but it's low-priority (and definitely not a blocker, so we shouldn't work on that right now): #176
