### ISSUE TITLE
Make the optional parameters truly optional

### ISSUE THREAD

**Issue by yrodiere** [mincong-h/gsoc-hsearch#181]
Currently the parameters must always be provided, because we expect them to be non-null and thus we don't do any null-check.

That's not obvious because we always use `BatchIndexingJob.Builder` in our tests, and this builder automatically adds default values to every parameter (an empty string for "hql", 200 for "itemCount", etc.).

If we want to allow to launch the job from the command line, we must move the default value handling out of `BatchIndexingJob.Builder` and into the actual job.

**Comment by mincong-h** [comment]
> Currently the parameters must always be provided, because we expect them to be non-null and thus we don't do any null-check.
> 
> That's not obvious because we always use BatchIndexingJob.Builder in our tests, and this builder automatically adds default values to every parameter (an empty string for "hql", 200 for "itemCount", etc.).

Yes, you're right. I didn't think about that.

> If we want to allow to launch the job from the command line, we must move the default value handling out of `BatchIndexingJob.Builder` and into the actual job.

I agree with you. The default values should be handled in the job instead of `BatchIndexingJob.Builder`. According to the spec _8.8.1.5 Substitution Expression Default_: Substitutions expressions may include a default value using the `"?:"` operator. The default is applied if the substitution's principle value expression resolves to the empty string `""`. For example, for property `itemCount`, we can use the `"?:"` operator to define its default value in Job XML:

```xml
<!--
    Read property 'itemCount' from job parameters.
    Set to 200 if not found.
 -->
<property name="itemCount" value="#{jobParameters['itemCount']}?:200;" />
```

Actually, this substitution expression is already present in the current implementation as we can see in [`BatchIndexingJob.xml`][1]. So the next steps should be:

- [ ] Complete the missing default values in [`BatchIndexingJob.xml`][1]
- [ ] Remove the default-value handling in `BatchIndexingJob.Builder`
- [ ] Add / modify relate unit tests

[1]: https://github.com/mincong-h/gsoc-hsearch/blob/65aa7fec8d2a0e5c35f600cb5bad9ef822a08d45/core/src/main/resources/META-INF/batch-jobs/BatchIndexingJob.xml

**Comment by yrodiere** [comment]
Closing, moved to JIRA: https://hibernate.atlassian.net/browse/HSEARCH-2623
