### ISSUE TITLE
Make use of checkpoints to continue processing after a failure

### ISSUE THREAD

**Issue by gunnarmorling** [mincong-h/gsoc-hsearch#40]
For that we'd need to order the items by id, remember the last id processed in a check point and the continue after that.

**Comment by mincong-h** [comment]
Thanks for this. I've mentioned it at issue _#3 The current batch processing design is bad_, but never open it as an issue. This will be done in the future.

**Comment by gunnarmorling** [comment]
Ok, cool. That'll be a more interesting one after all the "infrastructure" issues I created recently. Using checkpoints ensures restart-ability of the batch job without re-indexing everything again, which is a nice advantage over the current implementation.

**Comment by mincong-h** [comment]
The integration test `RestartChunkIT` demonstrates the job `mass-index` can be started, stopped and restarted again. The current checkpoint is set to the chunk step `produceLuceneDoc`. When the job is stopped, the production of Lucene docs will be stopped too. However, the bulks of entity IDs are serialised. Then, when the job is restarted, it skips the previous steps and resumes directly at step `produceLuceneDoc` using the checkpoint.

Imagine the below scenario, there's 100 entities need to be indexed : 

*  **The first job** has indexed 13 entities, then stopped.
   *  Entity with ID from 1 to 12 are persisted because there's 1 checkpoint each 3 items
   *  Entity with ID=13 is not registered because the next checkpoint would be at ID=15.
   *  I registered specifically this entity ID=13 when `#close()` is called.
*  **The second job** resumes the work from ID=13 (Not ID=12) and processes until the end.
   * using `#open(Serializable)`
   * previous steps are skipped
   * entity ID=13 is the intersection part for these 2 launches. It has been indexed twice.

Here's the log : 

First start : 

```log
Jul 05, 2016 2:11:05 AM org.hibernate.search.jsr352.se.RestartChunkIT testBatchStatus
INFO: metrics in step produceLuceneDoc:

	COMMIT_COUNT: 5
	READ_SKIP_COUNT: 0
	READ_COUNT: 13
	PROCESS_SKIP_COUNT: 0
	ROLLBACK_COUNT: 0
	WRITE_COUNT: 13
	FILTER_COUNT: 0
	WRITE_SKIP_COUNT: 0

Jul 05, 2016 2:11:05 AM org.hibernate.search.jsr352.se.RestartChunkIT testJob
INFO: Job (executionId=2) STOPPED, executed steps:

	id=loadId, status=COMPLETED
	id=produceLuceneDoc, status=STOPPED

Jul 05, 2016 2:11:05 AM org.hibernate.search.jsr352.se.RestartChunkIT keepTestAlive
INFO: Job (id=3) STARTING, thread sleep 1000 ms...
```

Second start : 

```log
Jul 05, 2016 2:11:06 AM org.hibernate.search.jsr352.se.RestartChunkIT testBatchStatus
INFO: metrics in step produceLuceneDoc:

	COMMIT_COUNT: 30
	READ_SKIP_COUNT: 0
	READ_COUNT: 88
	PROCESS_SKIP_COUNT: 0
	ROLLBACK_COUNT: 0
	WRITE_COUNT: 88
	FILTER_COUNT: 0
	WRITE_SKIP_COUNT: 0

Jul 05, 2016 2:11:06 AM org.hibernate.search.jsr352.se.RestartChunkIT testJob
INFO: Job (executionId=3) stopped, executed steps:

	id=produceLuceneDoc, status=COMPLETED

Jul 05, 2016 2:11:06 AM org.hibernate.search.jsr352.se.RestartChunkIT testJob
INFO: finished
```

**Comment by mincong-h** [comment]
Done. More checkpoint will be covered in the future, marked as issue #83.
