### ISSUE TITLE
Remove .classpath from repo (add it to .gitignore)

### ISSUE THREAD

**Issue by gunnarmorling** [mincong-h/gsoc-hsearch#43]
No dot files nor the .settings directory should be part of the repo apart from .gitignore.

**Comment by mincong-h** [comment]
The file [`.gitignore`][1] has been modified in commit 522f1ac and 3 git ignore templates had been added for Java / Mac / Eclipse. Since this commit, not more platform-depend "meta" data file appears in the git repo.

[1]: https://github.com/mincong-h/gsoc-hsearch/blob/522f1ac1c3e4f5086d1c9d17631cafd54bf0a5a0/.gitignore
