### ISSUE TITLE
How to handle scope "provided" for Java SE and Java EE

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#72]
Sometime, a dependency can be provided by the Java EE container, but obviously cannot be provided by Java SE. In this case, how to write the pom file ?

Should we do the below operation ? 
-  write the dependency in the tag `<dependencies>`, without defining the scope
-  use a profile for Java SE and use another profile for Java EE
-  write the same dependency in the Java EE profile, but overwrite its scope to `provided`

**Comment by mincong-h** [comment]
Maybe I need to use 2 relative pom.xml file, because tests in Java SE and Java EE are different : 

*  In Java SE, we deploy a JAR file
*  In Java EE, we deploy a WAR file

Am I right ?

**Comment by yrodiere** [comment]
@mincong-h Could you please tell me what are the dependencies you're worried about?

The only questionable dependency I could find was `javax.inject:javax.inject`.
Other dependencies either have the `test` scope or are required by test modules, thus they don't affect users' dependency hierarchies, thus we don't care.

If it's only about `javax.inject:javax.inject`, let's close this ticket and discuss it on #86.

**Comment by mincong-h** [comment]
When we search keyword _provided_ in the repo on the master branch, you'll find these dependencies having the provided scope:

- org.jboss.spec.javax.batch:jboss-batch-api_1.0_spec
- javax.inject:provided
- javax.enterprise:cdi-api

I think most of them are configured by @gunnarmorling at the beginning, or I copied from JBeret.

> Could you please tell me what are the dependencies you're worried about?

Actually, this issue is a newbie question for learning maven.  I don't understand what's the behaviour behind the screen for Java SE with these provided-scope dependencies. As nobody is providing these artifacts in Java SE, how does our project compiles? What happens when Java SE users use our project? Will it throw a ClassNotFoundException, because those classes are provided but nobody provides anything?

**Comment by yrodiere** [comment]
The scope "provided" means "fetch and use this dependency when compiling, but do not make that a transitive runtime dependency for consumers of my maven artifact; they will *provide* their own version of this dependency". See https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope

When searching for the "provided" keyword in poms, I get that result:

```
$ grep -r provided --include=pom.xml . -B 3
./integrationtest/performance/pom.xml-            <groupId>org.jboss.ejb3</groupId>
./integrationtest/performance/pom.xml-            <artifactId>jboss-ejb3-ext-api</artifactId>
./integrationtest/performance/pom.xml-            <version>2.1.0</version>
./integrationtest/performance/pom.xml:            <scope>provided</scope>
--
./integrationtest/wildfly/pom.xml-            <groupId>org.jboss.ejb3</groupId>
./integrationtest/wildfly/pom.xml-            <artifactId>jboss-ejb3-ext-api</artifactId>
./integrationtest/wildfly/pom.xml-            <version>2.1.0</version>
./integrationtest/wildfly/pom.xml:            <scope>provided</scope>
--
./core/pom.xml-        <dependency>
./core/pom.xml-            <groupId>org.jboss.spec.javax.batch</groupId>
./core/pom.xml-            <artifactId>jboss-batch-api_1.0_spec</artifactId>
./core/pom.xml:            <scope>provided</scope>
--
./core/pom.xml-        <dependency>
./core/pom.xml-            <groupId>javax.inject</groupId>
./core/pom.xml-            <artifactId>javax.inject</artifactId>
./core/pom.xml:            <scope>provided</scope>
```

The first two dependencies are in integration test modules, so their scope will not affect users. In short, they don't matter.

The last two dependencies are in the core. `org.jboss.spec.javax.batch:jboss-batch-api_1.0_spec` is the artifact for the JSR-352 API, so it should stay here.
The scope is "provided" because users are expected to have a runtime dependency to a JSR-352 implementation that will provide its own (probably identical) version of the JSR-352 API. Thus we don't need to make this dependency transitive.

The `javax.inject:javax.inject` dependency is "provided" for the same reason.
I don't know why there is an explicit dependency to `javax.inject:javax.inject`, though: the JSR-352 API already depends on `javax.inject:javax.inject`, so there shouldn't be a need for an explicit dependency. I think we should remove it.

**Comment by mincong-h** [comment]
Thanks for your very detailed explanation. Previously, I thought that artifacts having `provided` scope can only be provided by Java container at runtime, but this is wrong: they can be provided by any implementation, e.g the batch runtime! So things are very clear now. I'll try change the dependencies and check the results.
