### ISSUE TITLE
Dubious item-count = 3

### ISSUE THREAD

**Issue by gunnarmorling** [mincong-h/gsoc-hsearch#90]
Why is the item count set to 3 in _mass-index.xml_, `produceLuceneDoc`?

**Comment by mincong-h** [comment]
It was set to 3 because greater values involes out of memory (issue #19) : 

In earlier version of the project, when the target entities was `Address`, we've the below params : 

- array capacity = 500. That means an "item" is a bulk of 500 IDs.
- item count = 3.

Since the writer `BatchItemWriter` writes when item count reaches, it writes 

    3 items * 500 IDs / item * 1 LuceneWork / ID= 1500 LuceneWorks

for each time. And comparint to the current set up in Hibernate Search (1 work each time), this value is really high. If I increase the item count greater than 3, then the issues #19 appears.

But I think it shoul be changed dynamically by the user in the future

**Comment by mincong-h** [comment]
I'm thinking about to implement a customized checkpoint algorithm [`CheckpointAlgorithm`][1] to accept dynamique checkpoint.

[1]: https://docs.oracle.com/javaee/7/api/javax/batch/api/chunk/CheckpointAlgorithm.html

**Comment by mincong-h** [comment]
The checkpoint is no longer static. Users can defined their own checkpoint frequency throw method `MassIndexer#checkpointFreq(int)`. And inside the job XML file, the previous item-count is replaced by the `CheckpointAlgorithm`.

Previous (static) : 

```xml
<chunk item-count="3">
    ...
</chunk>
```

Now (dynamic) : 

```xml
<chunk checkpoint-policy="custom">
    ...
    <checkpoint-algorithm ref="checkpointAlgorithm">
        <properties>
            <property name="itemCount" value="#{jobParameters['itemCount']}?:3;" />
        </properties>
    </checkpoint-algorithm>
</chunk>
```
